# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- $appName        := "capi-providers-config" }}
{{- $namespace      := "capi-operator-system" }}
{{- $syncWave       := "1100" }}
---
{{- if (index .Values.argo.enabled $appName) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $syncWave }}"
  name: {{$appName}}
  namespace: {{ required "A valid namespace entry required!" .Values.argo.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ required "A valid projectName entry required!" .Values.argo.project }}
  source:
    repoURL: https://github.com/open-edge-platform/orch-utils
    path: charts/capi-operator-providers-config
    targetRevision: main
    helm:
      releaseName: {{$appName}}
      values: |
        core:
          name: cluster-api
          namespace: capi-system
          spec:
            version: v1.9.0
            configSecret:
              namespace: capi-variables
              name: capi-variables
            manager:
              featureGates:
                MachinePool: true
                ClusterResourceSet: true
                ClusterTopology: true
                RuntimeSDK: false
                MachineSetPreflightChecks: true
                MachineWaitForVolumeDetachConsiderVolumeAttachments: true
        bootstrap:
          name: rke2
          namespace: capr-system
          spec:
            version: v0.12.0
            configSecret:
              namespace: capi-variables
              name: capi-variables
        controlPlane:
          name: rke2
          namespace: capr-system
          spec:
            version: v0.12.0
            configSecret:
              namespace: capi-variables
              name: capi-variables
            deployment:
              containers:
              - name: manager
                imageUrl: docker.io/andybavier/cluster-api-provider-rke2-controlplane:latest
                args:
                  "--concurrency": "5"
  destination:
    namespace: {{$namespace}}
    server: {{ required "A valid targetServer entry required!" .Values.argo.targetServer }}
  syncPolicy:
    {{- if .Values.argo.autosync }}
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
