# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- $clusterDomain := include "keycloak-instance.clusterDomain" . }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-keycloak-ingress
  namespace: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: platform-keycloak
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - secretName: keycloak-tls
      hosts:
        - keycloak.{{ $clusterDomain }}
  rules:
    - host: keycloak.{{ $clusterDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-keycloak-service
                port:
                  number: 8080
