# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: platform-keycloak
  namespace: keycloak-system
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: platform-keycloak
    app.kubernetes.io/version: "26.4.2"
  annotations:
    description: "Service for Keycloak platform-keycloak instance"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: keycloak
    app.kubernetes.io/instance: platform-keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  ports:
    - name: http-default
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: management
      port: 9000
      targetPort: 9000
      protocol: TCP
