# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

caSecretName: gateway-ca-cert
caSecretKey: ca.crt

openPolicyAgent:
  image:
    tag: 1.10.1-static
  config:
    profile: "compressed"

istio-proxy:
  securityContext:
    readOnlyRootFilesystem: true

# https://doc.traefik.io/traefik/migrate/v2-to-v3-details/#kubernetes-crds-api-group-traefikcontainous
traefikApiGroup: "traefik.io/v1alpha1"

alertmanager:
  configmapReload:
    tag: v0.86.2
