# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

configProvisioner:
  useM2MToken: true
  catalogServer: app-orch-catalog-grpc-server.orch-app.svc.cluster.local:8080
  admServer: app-deployment-api-grpc-server.orch-app.svc.cluster.local:8080
  namespace: orch-app
  vaultServer: "http://vault.orch-platform.svc.cluster.local:8200"
  keycloakServiceBase: "http://platform-keycloak.orch-platform.svc.cluster.local:8080"
  releaseServiceBase: "files-rs.edgeorchestration.intel.com"
  releaseServiceProxyRootUrl: "oci://registry-rs.edgeorchestration.intel.com"
  manifestPath: "/edge-orch/en/file/cluster-extension-manifest"
  serviceAccount: "orch-svc"
resources: null
