# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

resources: null

jwksURL: "http://platform-keycloak.orch-platform.svc.cluster.local/realms/master/protocol/openid-connect/certs"
