# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Enable serviceMonitor for the gateway
gateway:
  metrics:
    serviceMonitor:
      enabled: true

# Enable serviceMonitor for the controller
controller:
  metrics:
    serviceMonitor:
      enabled: true

# https://doc.traefik.io/traefik/migrate/v2-to-v3-details/#kubernetes-crds-api-group-traefikcontainous
traefikApiGroup: "traefik.io/v1alpha1"

openpolicyagent:
  tag: 1.10.1-static
