# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Sync the Keycloak database credentials from orch-database namespace to keycloak-system
# Source: keycloak-system-platform-keycloak secret (created by PostgreSQL initdb)
# Target: keycloak-platform-db secret (used by Keycloak CRD)
remoteNamespace: orch-database
refreshInterval: "0m"
targetSecretName: keycloak-platform-db
sourceSecretName: keycloak-system-platform-keycloak
keyName:
  - source: username
    target: username
  - source: password
    target: password

externalSecretsApiGroup: external-secrets.io/v1