# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

manager:
  inventory:
    endpoint: "inventory.orch-infra.svc.cluster.local:50051"
oidc:
  oidc_server_url: "http://platform-keycloak.keycloak-system.svc.cluster.local:8080/realms/master"  # Overridden in template based on clusterDomain
traefikApiGroup: "traefik.io/v1alpha1"
