# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Intentionally blank. There are no base settings overrides.

openidc:
  # This value is overridden in the template based on clusterDomain
  issuer: "http://platform-keycloak.orch-platform.svc:8080/realms/master"

service:
  traefik:
    namespace: "orch-gateway"

openpolicyagent:
  tag: 1.10.0-static
