# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Intentionally blank. There are no base settings overrides.

openidc:
  issuer: https://keycloak.{{ .Values.argo.clusterDomain }}/realms/master

service:
  traefik:
    namespace: "orch-gateway"
