# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Intentionally blank. There are no base settings overrides.

openidc:
  issuer: http://platform-keycloak.keycloak-system.svc.cluster.local/realms/master

service:
  traefik:
    namespace: "orch-gateway"
