# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Intentionally blank. There are no base settings overrides.

openidc:
  issuer: >-
    {{ if or (contains "kind.internal" .Values.argo.clusterDomain) (contains "localhost" .Values.argo.clusterDomain) (eq .Values.argo.clusterDomain "") -}}
    http://platform-keycloak.orch-platform.svc.cluster.local:8080/realms/master
    {{- else -}}
    https://keycloak.{{ .Values.argo.clusterDomain }}/realms/master
    {{- end }}

service:
  traefik:
    namespace: "orch-gateway"
