# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Intentionally blank. There are no base settings overrides.

speaker:
  frr:
    enabled: false
  memberlist:
    enabled: false
