# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

auth:
  orchSvcs:
    roleMaxTTL: 1h
  oidc:
    idPAddr: "https://keycloak.{{ .Values.argo.clusterDomain }}"
    idPDiscoveryURL: "https://keycloak.{{ .Values.argo.clusterDomain }}/realms/master"
    roleMaxTTL: 1h
