# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

auth:
  orchSvcs:
    roleMaxTTL: 1h
  oidc:
    idPAddr: "http://platform-keycloak.keycloak-system.svc.cluster.local"
    idPDiscoveryURL: "http://platform-keycloak.keycloak-system.svc.cluster.local/realms/master"
    roleMaxTTL: 1h
