# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Note: Keycloak URLs are set dynamically in the template based on clusterDomain
# For local domains (kind.internal, localhost): uses internal Keycloak URL
# For external domains: uses external Keycloak URL
auth:
  orchSvcs:
    roleMaxTTL: 1h
  oidc:
    # These values are overridden in the template based on clusterDomain
    idPAddr: "http://platform-keycloak.keycloak-system.svc.cluster.local:8080"
    idPDiscoveryURL: "http://platform-keycloak.keycloak-system.svc.cluster.local:8080/realms/master"
    roleMaxTTL: 1h
