# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

auth:
  orchSvcs:
    roleMaxTTL: 1h
  oidc:
    idPAddr: >-
      {{ if or (contains "kind.internal" .Values.argo.clusterDomain) (contains "localhost" .Values.argo.clusterDomain) (eq .Values.argo.clusterDomain "") -}}
      http://platform-keycloak.orch-platform.svc.cluster.local:8080
      {{- else -}}
      https://keycloak.{{ .Values.argo.clusterDomain }}
      {{- end }}
    idPDiscoveryURL: >-
      {{ if or (contains "kind.internal" .Values.argo.clusterDomain) (contains "localhost" .Values.argo.clusterDomain) (eq .Values.argo.clusterDomain "") -}}
      http://platform-keycloak.orch-platform.svc.cluster.local:8080/realms/master
      {{- else -}}
      https://keycloak.{{ .Values.argo.clusterDomain }}/realms/master
      {{- end }}
    roleMaxTTL: 1h
