# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

tlsOption: "gateway-tls"

# https://doc.traefik.io/traefik/migrate/v2-to-v3-details/#kubernetes-crds-api-group-traefikcontainous
traefikApiGroup: "traefik.io/v1alpha1"

# Maintenance mode middleware configuration
# This will be created as a Traefik Middleware CRD
# The middleware is applied globally via traefik.tpl entrypoint configuration
maintenanceMode:
  enabled: true
  triggerFilename: /var/run/maintenance/maintenance.trigger
  httpResponseCode: 503
  httpContentType: 'text/html; charset=utf-8'
