# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

write-kubeconfig-mode: "0644"
audit-policy-file: "/etc/rancher/rke2/audit-policy.yaml"
cni:
  - calico
disable:
  - rke2-canal
  - rke2-ingress-nginx
  - rke2-snapshot-controller
  - rke2-snapshot-validation-webhook
kubelet-arg:
  - "max-pods=200"
etcd-arg:
  - --debug=false
  - --log-package-levels=INFO
  - --config-file=/var/lib/rancher/rke2/server/db/etcd/config
  - --quota-backend-bytes=8589934592
  - --auto-compaction-mode=periodic
  - --auto-compaction-retention=1h
services:
  kubelet:
    extra_binds:
      - /var/openebs/local:/var/openebs/local