# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Common values shared among multiple components
argo:
  database:
    databases:
      - namespace: orch-app
        name: app-orch-catalog
      - namespace: orch-platform
        name: platform-keycloak
      - namespace: orch-platform
        name: vault
      - namespace: orch-infra
        name: inventory
      - namespace: orch-infra
        name: alerting
      - namespace: orch-iam
        name: iam-tenancy
      - namespace: orch-infra
        name: mps
      - namespace: orch-infra
        name: rps
  traefik:
    tlsOption: "gateway-tls"
  namespaceLabels:
    orch-infra:
      istio-injection: enabled
    orch-iam:
      istio-injection: enabled
    orch-app:
      istio-injection: enabled
    orch-cluster:
      istio-injection: enabled
    orch-ui:
      istio-injection: enabled
    orch-platform:
      istio-injection: enabled
    orch-harbor:
      istio-injection: enabled
    orch-gateway:
      istio-injection: enabled
    orch-sre:
      istio-injection: enabled
    orch-database:
      istio-injection: enabled
    orch-boots:
      istio-injection: enabled
    orch-secret:
      istio-injection: enabled
    fleet-default:
      app.edge-orchestrator.intel.com/fleet-rs-secret: "true"
